/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZentraAiRouteImport } from './routes/zentra-ai'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as StepsRouteImport } from './routes/steps'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FormCorrectionRouteImport } from './routes/form-correction'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as StepsIndexRouteImport } from './routes/steps.index'
import { Route as MealsIndexRouteImport } from './routes/meals.index'
import { Route as FormCorrectionIndexRouteImport } from './routes/form-correction.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as WorkoutsHistoryRouteImport } from './routes/workouts.history'
import { Route as StepsHistoryRouteImport } from './routes/steps.history'
import { Route as SessionsHistoryRouteImport } from './routes/sessions.history'
import { Route as MealsWeeklyRouteImport } from './routes/meals.weekly'
import { Route as MealsShoppingRouteImport } from './routes/meals.shopping'
import { Route as MealsRecipeRouteImport } from './routes/meals.recipe'
import { Route as MealsHistoryRouteImport } from './routes/meals.history'
import { Route as MealsDailyRecipesRouteImport } from './routes/meals.daily-recipes'
import { Route as FormCorrectionGroupRouteImport } from './routes/form-correction.$group'
import { Route as BlogsIdRouteImport } from './routes/blogs.$id'
import { Route as FormCorrectionGroupIndexRouteImport } from './routes/form-correction.$group.index'
import { Route as FormCorrectionGroupExerciseRouteImport } from './routes/form-correction.$group.$exercise'

const ZentraAiRoute = ZentraAiRouteImport.update({
  id: '/zentra-ai',
  path: '/zentra-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const StepsRoute = StepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FormCorrectionRoute = FormCorrectionRouteImport.update({
  id: '/form-correction',
  path: '/form-correction',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutsRoute,
} as any)
const StepsIndexRoute = StepsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StepsRoute,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MealsRoute,
} as any)
const FormCorrectionIndexRoute = FormCorrectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormCorrectionRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const WorkoutsHistoryRoute = WorkoutsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WorkoutsRoute,
} as any)
const StepsHistoryRoute = StepsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StepsRoute,
} as any)
const SessionsHistoryRoute = SessionsHistoryRouteImport.update({
  id: '/sessions/history',
  path: '/sessions/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsWeeklyRoute = MealsWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => MealsRoute,
} as any)
const MealsShoppingRoute = MealsShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => MealsRoute,
} as any)
const MealsRecipeRoute = MealsRecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => MealsRoute,
} as any)
const MealsHistoryRoute = MealsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MealsRoute,
} as any)
const MealsDailyRecipesRoute = MealsDailyRecipesRouteImport.update({
  id: '/daily-recipes',
  path: '/daily-recipes',
  getParentRoute: () => MealsRoute,
} as any)
const FormCorrectionGroupRoute = FormCorrectionGroupRouteImport.update({
  id: '/$group',
  path: '/$group',
  getParentRoute: () => FormCorrectionRoute,
} as any)
const BlogsIdRoute = BlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogsRoute,
} as any)
const FormCorrectionGroupIndexRoute =
  FormCorrectionGroupIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => FormCorrectionGroupRoute,
  } as any)
const FormCorrectionGroupExerciseRoute =
  FormCorrectionGroupExerciseRouteImport.update({
    id: '/$exercise',
    path: '/$exercise',
    getParentRoute: () => FormCorrectionGroupRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/form-correction': typeof FormCorrectionRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/steps': typeof StepsRouteWithChildren
  '/workouts': typeof WorkoutsRouteWithChildren
  '/zentra-ai': typeof ZentraAiRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/form-correction/$group': typeof FormCorrectionGroupRouteWithChildren
  '/meals/daily-recipes': typeof MealsDailyRecipesRoute
  '/meals/history': typeof MealsHistoryRoute
  '/meals/recipe': typeof MealsRecipeRoute
  '/meals/shopping': typeof MealsShoppingRoute
  '/meals/weekly': typeof MealsWeeklyRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/steps/history': typeof StepsHistoryRoute
  '/workouts/history': typeof WorkoutsHistoryRoute
  '/blogs/': typeof BlogsIndexRoute
  '/form-correction/': typeof FormCorrectionIndexRoute
  '/meals/': typeof MealsIndexRoute
  '/steps/': typeof StepsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/form-correction/$group/$exercise': typeof FormCorrectionGroupExerciseRoute
  '/form-correction/$group/': typeof FormCorrectionGroupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/zentra-ai': typeof ZentraAiRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/meals/daily-recipes': typeof MealsDailyRecipesRoute
  '/meals/history': typeof MealsHistoryRoute
  '/meals/recipe': typeof MealsRecipeRoute
  '/meals/shopping': typeof MealsShoppingRoute
  '/meals/weekly': typeof MealsWeeklyRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/steps/history': typeof StepsHistoryRoute
  '/workouts/history': typeof WorkoutsHistoryRoute
  '/blogs': typeof BlogsIndexRoute
  '/form-correction': typeof FormCorrectionIndexRoute
  '/meals': typeof MealsIndexRoute
  '/steps': typeof StepsIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/form-correction/$group/$exercise': typeof FormCorrectionGroupExerciseRoute
  '/form-correction/$group': typeof FormCorrectionGroupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/form-correction': typeof FormCorrectionRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/steps': typeof StepsRouteWithChildren
  '/workouts': typeof WorkoutsRouteWithChildren
  '/zentra-ai': typeof ZentraAiRoute
  '/blogs/$id': typeof BlogsIdRoute
  '/form-correction/$group': typeof FormCorrectionGroupRouteWithChildren
  '/meals/daily-recipes': typeof MealsDailyRecipesRoute
  '/meals/history': typeof MealsHistoryRoute
  '/meals/recipe': typeof MealsRecipeRoute
  '/meals/shopping': typeof MealsShoppingRoute
  '/meals/weekly': typeof MealsWeeklyRoute
  '/sessions/history': typeof SessionsHistoryRoute
  '/steps/history': typeof StepsHistoryRoute
  '/workouts/history': typeof WorkoutsHistoryRoute
  '/blogs/': typeof BlogsIndexRoute
  '/form-correction/': typeof FormCorrectionIndexRoute
  '/meals/': typeof MealsIndexRoute
  '/steps/': typeof StepsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/form-correction/$group/$exercise': typeof FormCorrectionGroupExerciseRoute
  '/form-correction/$group/': typeof FormCorrectionGroupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/dashboard'
    | '/form-correction'
    | '/history'
    | '/login'
    | '/meals'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/steps'
    | '/workouts'
    | '/zentra-ai'
    | '/blogs/$id'
    | '/form-correction/$group'
    | '/meals/daily-recipes'
    | '/meals/history'
    | '/meals/recipe'
    | '/meals/shopping'
    | '/meals/weekly'
    | '/sessions/history'
    | '/steps/history'
    | '/workouts/history'
    | '/blogs/'
    | '/form-correction/'
    | '/meals/'
    | '/steps/'
    | '/workouts/'
    | '/form-correction/$group/$exercise'
    | '/form-correction/$group/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/zentra-ai'
    | '/blogs/$id'
    | '/meals/daily-recipes'
    | '/meals/history'
    | '/meals/recipe'
    | '/meals/shopping'
    | '/meals/weekly'
    | '/sessions/history'
    | '/steps/history'
    | '/workouts/history'
    | '/blogs'
    | '/form-correction'
    | '/meals'
    | '/steps'
    | '/workouts'
    | '/form-correction/$group/$exercise'
    | '/form-correction/$group'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/dashboard'
    | '/form-correction'
    | '/history'
    | '/login'
    | '/meals'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/steps'
    | '/workouts'
    | '/zentra-ai'
    | '/blogs/$id'
    | '/form-correction/$group'
    | '/meals/daily-recipes'
    | '/meals/history'
    | '/meals/recipe'
    | '/meals/shopping'
    | '/meals/weekly'
    | '/sessions/history'
    | '/steps/history'
    | '/workouts/history'
    | '/blogs/'
    | '/form-correction/'
    | '/meals/'
    | '/steps/'
    | '/workouts/'
    | '/form-correction/$group/$exercise'
    | '/form-correction/$group/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FormCorrectionRoute: typeof FormCorrectionRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MealsRoute: typeof MealsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StepsRoute: typeof StepsRouteWithChildren
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
  ZentraAiRoute: typeof ZentraAiRoute
  SessionsHistoryRoute: typeof SessionsHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zentra-ai': {
      id: '/zentra-ai'
      path: '/zentra-ai'
      fullPath: '/zentra-ai'
      preLoaderRoute: typeof ZentraAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steps': {
      id: '/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof StepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-correction': {
      id: '/form-correction'
      path: '/form-correction'
      fullPath: '/form-correction'
      preLoaderRoute: typeof FormCorrectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/steps/': {
      id: '/steps/'
      path: '/'
      fullPath: '/steps/'
      preLoaderRoute: typeof StepsIndexRouteImport
      parentRoute: typeof StepsRoute
    }
    '/meals/': {
      id: '/meals/'
      path: '/'
      fullPath: '/meals/'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof MealsRoute
    }
    '/form-correction/': {
      id: '/form-correction/'
      path: '/'
      fullPath: '/form-correction/'
      preLoaderRoute: typeof FormCorrectionIndexRouteImport
      parentRoute: typeof FormCorrectionRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/workouts/history': {
      id: '/workouts/history'
      path: '/history'
      fullPath: '/workouts/history'
      preLoaderRoute: typeof WorkoutsHistoryRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/steps/history': {
      id: '/steps/history'
      path: '/history'
      fullPath: '/steps/history'
      preLoaderRoute: typeof StepsHistoryRouteImport
      parentRoute: typeof StepsRoute
    }
    '/sessions/history': {
      id: '/sessions/history'
      path: '/sessions/history'
      fullPath: '/sessions/history'
      preLoaderRoute: typeof SessionsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/weekly': {
      id: '/meals/weekly'
      path: '/weekly'
      fullPath: '/meals/weekly'
      preLoaderRoute: typeof MealsWeeklyRouteImport
      parentRoute: typeof MealsRoute
    }
    '/meals/shopping': {
      id: '/meals/shopping'
      path: '/shopping'
      fullPath: '/meals/shopping'
      preLoaderRoute: typeof MealsShoppingRouteImport
      parentRoute: typeof MealsRoute
    }
    '/meals/recipe': {
      id: '/meals/recipe'
      path: '/recipe'
      fullPath: '/meals/recipe'
      preLoaderRoute: typeof MealsRecipeRouteImport
      parentRoute: typeof MealsRoute
    }
    '/meals/history': {
      id: '/meals/history'
      path: '/history'
      fullPath: '/meals/history'
      preLoaderRoute: typeof MealsHistoryRouteImport
      parentRoute: typeof MealsRoute
    }
    '/meals/daily-recipes': {
      id: '/meals/daily-recipes'
      path: '/daily-recipes'
      fullPath: '/meals/daily-recipes'
      preLoaderRoute: typeof MealsDailyRecipesRouteImport
      parentRoute: typeof MealsRoute
    }
    '/form-correction/$group': {
      id: '/form-correction/$group'
      path: '/$group'
      fullPath: '/form-correction/$group'
      preLoaderRoute: typeof FormCorrectionGroupRouteImport
      parentRoute: typeof FormCorrectionRoute
    }
    '/blogs/$id': {
      id: '/blogs/$id'
      path: '/$id'
      fullPath: '/blogs/$id'
      preLoaderRoute: typeof BlogsIdRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/form-correction/$group/': {
      id: '/form-correction/$group/'
      path: '/'
      fullPath: '/form-correction/$group/'
      preLoaderRoute: typeof FormCorrectionGroupIndexRouteImport
      parentRoute: typeof FormCorrectionGroupRoute
    }
    '/form-correction/$group/$exercise': {
      id: '/form-correction/$group/$exercise'
      path: '/$exercise'
      fullPath: '/form-correction/$group/$exercise'
      preLoaderRoute: typeof FormCorrectionGroupExerciseRouteImport
      parentRoute: typeof FormCorrectionGroupRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsIdRoute: typeof BlogsIdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsIdRoute: BlogsIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface FormCorrectionGroupRouteChildren {
  FormCorrectionGroupExerciseRoute: typeof FormCorrectionGroupExerciseRoute
  FormCorrectionGroupIndexRoute: typeof FormCorrectionGroupIndexRoute
}

const FormCorrectionGroupRouteChildren: FormCorrectionGroupRouteChildren = {
  FormCorrectionGroupExerciseRoute: FormCorrectionGroupExerciseRoute,
  FormCorrectionGroupIndexRoute: FormCorrectionGroupIndexRoute,
}

const FormCorrectionGroupRouteWithChildren =
  FormCorrectionGroupRoute._addFileChildren(FormCorrectionGroupRouteChildren)

interface FormCorrectionRouteChildren {
  FormCorrectionGroupRoute: typeof FormCorrectionGroupRouteWithChildren
  FormCorrectionIndexRoute: typeof FormCorrectionIndexRoute
}

const FormCorrectionRouteChildren: FormCorrectionRouteChildren = {
  FormCorrectionGroupRoute: FormCorrectionGroupRouteWithChildren,
  FormCorrectionIndexRoute: FormCorrectionIndexRoute,
}

const FormCorrectionRouteWithChildren = FormCorrectionRoute._addFileChildren(
  FormCorrectionRouteChildren,
)

interface MealsRouteChildren {
  MealsDailyRecipesRoute: typeof MealsDailyRecipesRoute
  MealsHistoryRoute: typeof MealsHistoryRoute
  MealsRecipeRoute: typeof MealsRecipeRoute
  MealsShoppingRoute: typeof MealsShoppingRoute
  MealsWeeklyRoute: typeof MealsWeeklyRoute
  MealsIndexRoute: typeof MealsIndexRoute
}

const MealsRouteChildren: MealsRouteChildren = {
  MealsDailyRecipesRoute: MealsDailyRecipesRoute,
  MealsHistoryRoute: MealsHistoryRoute,
  MealsRecipeRoute: MealsRecipeRoute,
  MealsShoppingRoute: MealsShoppingRoute,
  MealsWeeklyRoute: MealsWeeklyRoute,
  MealsIndexRoute: MealsIndexRoute,
}

const MealsRouteWithChildren = MealsRoute._addFileChildren(MealsRouteChildren)

interface StepsRouteChildren {
  StepsHistoryRoute: typeof StepsHistoryRoute
  StepsIndexRoute: typeof StepsIndexRoute
}

const StepsRouteChildren: StepsRouteChildren = {
  StepsHistoryRoute: StepsHistoryRoute,
  StepsIndexRoute: StepsIndexRoute,
}

const StepsRouteWithChildren = StepsRoute._addFileChildren(StepsRouteChildren)

interface WorkoutsRouteChildren {
  WorkoutsHistoryRoute: typeof WorkoutsHistoryRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsHistoryRoute: WorkoutsHistoryRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FormCorrectionRoute: FormCorrectionRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MealsRoute: MealsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StepsRoute: StepsRouteWithChildren,
  WorkoutsRoute: WorkoutsRouteWithChildren,
  ZentraAiRoute: ZentraAiRoute,
  SessionsHistoryRoute: SessionsHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
